version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./ACsetups:/app/ACsetups
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    networks:
      - appnet

networks:
  appnet:

volumes:
  frontend_build:
