version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
        - ./ACsetups:/ACsetups
    restart: always

  frontend:
    build: ./frontend
    restart: always

  reverse-proxy:
     image: nginx:alpine
     ports:
       - "80:80" # Map the host's port 80 to the container's port 80
     volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
     depends_on:
       - backend
       - frontend
     restart: always
